

POST  https://us-central1-read-write-share-36d59.cloudfunctions.net/api/signup
Content-Type: application/json


{
    "email": "md.mizan1@gmail.com",
    "password":"123456",
    "confirmPassword": "123456",
    "fullName": "Mizanur Rahaman",
    "gender": "male"
}



###
post https://us-central1-read-write-share-36d59.cloudfunctions.net/api/user
Content-Type: application/json
Authorization: Auth eyJhbGciOiJSUzI1NiIsImtpZCI6IjhjZjBjNjQyZDQwOWRlODJlY2M5MjI4ZTRiZDc5OTkzOTZiNTY3NDAiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcmVhZC13cml0ZS1zaGFyZS0zNmQ1OSIsImF1ZCI6InJlYWQtd3JpdGUtc2hhcmUtMzZkNTkiLCJhdXRoX3RpbWUiOjE1ODM4NjIyODgsInVzZXJfaWQiOiJRZ3VwbkxWbG1qUmo4a3QwQllCdWpMdWw5QzYzIiwic3ViIjoiUWd1cG5MVmxtalJqOGt0MEJZQnVqTHVsOUM2MyIsImlhdCI6MTU4Mzg2MjI4OCwiZXhwIjoxNTgzODY1ODg4LCJlbWFpbCI6Im1kLm1pemFuMUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsibWQubWl6YW4xQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.R9Lk8K2z3OOUj0wIJ6qiHZvsE-GsYLkUYV5EI47q0SR8VLQiCBgYVPKxK4lqrrbpPBMI3dnrzTDWsM9QQmYiwsbQvrpWJg17itnfkYwY9ul4sEGIBrchgg4OfRB_e1btKG0RsHOOvVoLVG_W4sPfENiax8qHlLscVP6JsJXvR6JQk8Ct5xSm2S1biHcA8-z7xkhG2dCMOQbXBp2M5tXbyFC4nAh-YsPE-o-Y643xarbobB4AaNZrlTrjHohvw1ZnFkXCJfOW55dfdvpaFHPBg9GUVDcH7VLHybjwtdYEgV-GNFMgUV1pJ-dVmEqQqvbowRg5JzXs8r3mHLK_63Wb3w


{
    "bio": "Hi I'm Miza",
    "website": "www.github.com/mizan4392",
    "location": "Kolabagan,Dhanmondi"
}


###
post https://us-central1-read-write-share-36d59.cloudfunctions.net/api/login
Content-Type: application/json



{
    "email": "md.mizan1@gmail.com",
    "password":"123456"
}

###
post https://us-central1-read-write-share-36d59.cloudfunctions.net/api/post
Content-Type: application/json
Authorization: Auth eyJhbGciOiJSUzI1NiIsImtpZCI6IjVlOWVlOTdjODQwZjk3ZTAyNTM2ODhhM2I3ZTk0NDczZTUyOGE3YjUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcmVhZC13cml0ZS1zaGFyZS0zNmQ1OSIsImF1ZCI6InJlYWQtd3JpdGUtc2hhcmUtMzZkNTkiLCJhdXRoX3RpbWUiOjE1ODgxMDEwNTUsInVzZXJfaWQiOiJRZ3VwbkxWbG1qUmo4a3QwQllCdWpMdWw5QzYzIiwic3ViIjoiUWd1cG5MVmxtalJqOGt0MEJZQnVqTHVsOUM2MyIsImlhdCI6MTU4ODEwMTA1NSwiZXhwIjoxNTg4MTA0NjU1LCJlbWFpbCI6Im1kLm1pemFuMUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsibWQubWl6YW4xQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.ielyzfjLUOTiTwsreb4BCvUJNNjTYWtFxCsZOU0FhskkTV328SyD4ImOqCltNdtyGT24BVXvFTf1PzzpMHVmFAsyTuQCRMoWtlDAeNIUarfkRb-iTl25kgn9k5DWlIOfId9e9ayksZds4b97LeZM7__aaS-VpzT-rwvXuKRpxWs6hHj8SVk9TrVaiIrKFRzfwJ58lf3JVaIDi-MwsW6XR28eRtl6C-shJTL-f99XiaWmxsLK3Dr_QotnbY1jXHRVihRRblGSwjDaIZZc253-tVvf0ObvXZXtkR9MbIoO_2TgPlEU9NXToGtAbYqGuqldaeHskNKEpFxDKMTw0SzIXg


{
    "body": "hoji biji hoji biji 2",
    "tags":"123456"
}

###
post https://us-central1-read-write-share-36d59.cloudfunctions.net/api/post/055dhM9zkmGcUtXZzy4M/comment
Content-Type: application/json
Authorization: Auth eyJhbGciOiJSUzI1NiIsImtpZCI6IjVlOWVlOTdjODQwZjk3ZTAyNTM2ODhhM2I3ZTk0NDczZTUyOGE3YjUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcmVhZC13cml0ZS1zaGFyZS0zNmQ1OSIsImF1ZCI6InJlYWQtd3JpdGUtc2hhcmUtMzZkNTkiLCJhdXRoX3RpbWUiOjE1ODgxMDEwNTUsInVzZXJfaWQiOiJRZ3VwbkxWbG1qUmo4a3QwQllCdWpMdWw5QzYzIiwic3ViIjoiUWd1cG5MVmxtalJqOGt0MEJZQnVqTHVsOUM2MyIsImlhdCI6MTU4ODEwMTA1NSwiZXhwIjoxNTg4MTA0NjU1LCJlbWFpbCI6Im1kLm1pemFuMUBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsibWQubWl6YW4xQGdtYWlsLmNvbSJdfSwic2lnbl9pbl9wcm92aWRlciI6InBhc3N3b3JkIn19.ielyzfjLUOTiTwsreb4BCvUJNNjTYWtFxCsZOU0FhskkTV328SyD4ImOqCltNdtyGT24BVXvFTf1PzzpMHVmFAsyTuQCRMoWtlDAeNIUarfkRb-iTl25kgn9k5DWlIOfId9e9ayksZds4b97LeZM7__aaS-VpzT-rwvXuKRpxWs6hHj8SVk9TrVaiIrKFRzfwJ58lf3JVaIDi-MwsW6XR28eRtl6C-shJTL-f99XiaWmxsLK3Dr_QotnbY1jXHRVihRRblGSwjDaIZZc253-tVvf0ObvXZXtkR9MbIoO_2TgPlEU9NXToGtAbYqGuqldaeHskNKEpFxDKMTw0SzIXg



{
    "body":"hoji biji hoji biji"
}



###
get https://us-central1-read-write-share-36d59.cloudfunctions.net/api/post/055dhM9zkmGcUtXZzy4M/getComment



###
